<a href="https://colab.research.google.com/github/PATELOM925/Probabilistic-Models-and-Machine-Learning/blob/main/EECS_6327_Week0_Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Basics: A Quick Review**


This is not a comprehensive review for *numpy* but just a quick highlight of some basic *numpy* functions.

Python's inborn data structures, such as lists and dictionaries, are not designed for high-performance scientific computations. An external package, named *numpy*, is created for this purpose. *Numpy* maintains its own multi-dimensional arrays and many convenient functions to manipulate these arrays in a very efficient mannor.


### **1. Create numpy arrays**

In [2]:
import numpy as np

# create an array using np.array()
array1 = np.array([[3, 4, 5],[0, 1, 2]])
print(array1)

# create an array filled with zeros using np.zeros()
array2 = np.zeros((3, 3))
print(array2)

# create an array filled with ones using np.ones()
array3 = np.ones((3, 4))
print(array3)

# create a random array
array4 = np.random.normal((3, 3))    # normally distributed using np.random.normal()
print(array4)

array5 = np.random.uniform(low=-1.0, high=1.0, size=(4,4)) # uniformly distributed
print(array5)

[[3 4 5]
 [0 1 2]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[3.11941972 1.16014764]
[[ 0.34719919 -0.16937987 -0.22686    -0.19896477]
 [-0.24759706 -0.96046948 -0.31318918 -0.70952729]
 [ 0.3460279  -0.28900342 -0.41010338 -0.50337563]
 [ 0.62269416 -0.61887895 -0.64032714  0.48367593]]


### **2. Manipulate numpy arrays**

In [3]:
# reshape or rearrange NumPy arrays

import numpy as np

# create a 1D array
array1 = np.array([1, 3, 5, 7, 9, 11])
print(array1)

# reshape the 1D array into a 2D array
array2 = np.reshape(array1, (2, 3))
print(array2)

# transpose the 2D array
array3 = np.transpose(array2)
print(array3)


[ 1  3  5  7  9 11]
[[ 1  3  5]
 [ 7  9 11]]
[[ 1  7]
 [ 3  9]
 [ 5 11]]


In [5]:
# Array Mathematical Functions
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
print(array1.shape)

# compute square root of array1 element-wise
arr_sqrt = np.sqrt(array1)
print(arr_sqrt)

# compute exponents of array2 element-wise
arr_exp= np.exp(array1)
print(arr_exp)

# sum arrays
arr_sum0 = np.sum(array1,0)   # sum along column
print(arr_sum0)

arr_sum1 = np.sum(array1,1)   # sum along row
print(arr_sum1)

arr_sum = np.sum(array1)      # sum all
print(arr_sum)

(2, 3)
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[5 7 9]
[ 6 15]
21


In [6]:
import numpy as np

# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the mean of marks
mean_marks = np.mean(marks)
print(mean_marks)

# compute the median of marks
median_marks = np.median(marks)
print(median_marks)

# find the minimum and maximum marks
min_marks = np.min(marks)
print(min_marks)

max_marks = np.max(marks)
print(max_marks)

77.2
78.0
66
85


### **3. Matrix multiplication and inner-product**

In [10]:
import numpy as np

v1 = np.random.normal(size =(5,5))   # random vector1
print(v1)

v2 = np.random.normal(size =(5,5))   # random vector2
print(v2)

dot12 = np.dot(v1, v2)   # inner-product of two vectors
print(dot12)

v12 = v1 * v2         # element-wise multiplication
print(np.sum(v1*v2))  # another way to compute inner-product

dot11 = np.dot(v1, v1)   # L2 norm of a vector
print(dot11)

[[ 1.05265109 -0.43558575 -0.38825479  0.10928061  0.65658983]
 [ 0.13845848 -0.88871972  0.21661416 -0.19334491  1.23029115]
 [-0.82471456  0.90377807 -0.22700276 -1.14494104  0.5716267 ]
 [ 0.40787954 -1.29473403  0.4880181  -0.70643306  0.30574458]
 [ 1.90940905 -0.34974076 -0.64282148  1.28934758 -0.18780788]]
[[ 0.92919532  0.41553249  1.6644627   2.13027322 -2.9073038 ]
 [ 2.12299153 -0.37418499 -0.0413522  -1.82592602 -0.09642583]
 [-0.42917581 -0.02176689 -2.43106564 -0.91042338  1.03247428]
 [-0.24914341 -0.2132857   0.54790983 -0.23398876  0.02842822]
 [-0.18461976 -0.4938023  -0.15324946  0.75511886  0.57800307]]
[[ 0.07155719  0.26131792  2.67323768  3.86149095 -3.0366203 ]
 [-2.03002047 -0.18091833 -0.55387079  2.69473684  0.61241884]
 [ 1.4295373  -0.71400577 -1.57314717 -2.50088119  2.37402707]
 [-2.45959853  0.6430293  -0.88788047  3.18485122 -0.40047911]
 [ 1.02104129  0.75602203  5.49057158  4.84789332 -6.25310444]]
3.2450790499286493
[[ 2.66623506 -0.79342789 -0.7836

In [16]:
import numpy as np

A = np.random.normal(size =(5, 5))   # random 5x5 matrix
print(A)

B = np.triu(np.ones((5,5)))         # upper triangular matrix
print(B)

B2 = np.tril(np.ones((5,5)))         # upper triangular matrix
print(B2)

v = np.random.normal(size =(5))   # random vector
print(v)

res1 = A * B      # element-wise multiplication of two matrice
print(res1)

res2 = A @ B      # MATRIX MULTIPLICATION
print(res2)

res3 = v @ A      # matrix multiplication
# print(res3)

res4 = B @ v      # matrix multiplication
# print(res4)


[[ 0.1410907   0.21422481  1.06159304 -0.2108711   0.37152439]
 [-1.68633017  1.53617759  0.02399721  1.53865775  0.7965674 ]
 [ 1.41038359  1.91320106  1.18814158 -0.56289813 -0.93702525]
 [ 1.93896801  1.3035791  -0.45450581  0.20265276  1.78272652]
 [ 1.02057691  0.69976376 -0.81053684  0.22945753  0.77641583]]
[[1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]
[ 0.8620458  -0.98567031 -0.50371057  0.43164628 -0.48398637]
[[ 0.1410907   0.21422481  1.06159304 -0.2108711   0.37152439]
 [-0.          1.53617759  0.02399721  1.53865775  0.7965674 ]
 [ 0.          0.          1.18814158 -0.56289813 -0.93702525]
 [ 0.          0.         -0.          0.20265276  1.78272652]
 [ 0.          0.         -0.          0.          0.77641583]]
[[ 0.1410907   0.35531551  1.41690855  1.20603745  1.57756183]
 [-1.68633017 -0.15015258 -0.12615538  1.41250238  2.20906977

### **Exercise**

1. Create a $5 \times 5$ normally distributed matrix (with mean $0$  and variance $0.1$), and then apply the sigmoid function $l(x) = \frac{1}{1 + e^{-x}}$ to it element-wisely.

2. Create a $3 \times 3$ uniformly distributed matrix (between $-1$ and $+1$), and then clip it by keeping all non-negative elements but setting all negative elements to $0$.

In [36]:
import numpy as np

print("Output 1")
#1
mean = 0
var = 0.1
m1 = np.random.normal(mean, var, size=(5, 5))
print(m1)

def sigmoid(x):
  return 1 / (1 + np.exp(-x))

m2 = sigmoid(m1)
print(m2)

#2
print("\nOutput 2")
m3 = np.random.uniform(-1, 1, size=(3, 3))
print(m3)

m3_clip = np.clip(m3, a_min=0,a_max=None)
print(m3_clip)

Output 1
[[-0.12311079  0.0924996  -0.00375828 -0.02274572 -0.04921465]
 [-0.03776941 -0.05384907 -0.05417217  0.2526569   0.0632932 ]
 [-0.13764155 -0.17990441  0.01908177  0.06358027  0.1124443 ]
 [-0.10105479  0.10966558  0.03517168 -0.07703625  0.23957704]
 [-0.19719881 -0.08038249 -0.01345693  0.00818655  0.16563031]]
[[0.46926112 0.52310843 0.49906043 0.49431382 0.48769882]
 [0.49055877 0.48654098 0.48646027 0.56283035 0.51581802]
 [0.46564384 0.45514481 0.5047703  0.51588972 0.52808149]
 [0.47475778 0.52738895 0.50879201 0.48075046 0.55960941]
 [0.45085944 0.47991519 0.49663582 0.50204663 0.54131317]]

Output 2
[[ 0.43717027  0.81094254 -0.27562752]
 [ 0.88076368  0.1750527   0.90237662]
 [ 0.44276607 -0.31821409  0.85993822]]
[[0.43717027 0.81094254 0.        ]
 [0.88076368 0.1750527  0.90237662]
 [0.44276607 0.         0.85993822]]
